name: Extract ZIP

on:
  push:
    paths:
      - 'extract.sh'

jobs:
  extract_zip:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract ZIP
      run: bash extract.sh
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Extract ZIP file
